"""imagem de empresa pode ser null

Revision ID: a06ac7904b47
Revises: a85e306a1c28
Create Date: 2021-06-26 22:25:31.077186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06ac7904b47'
down_revision = 'a85e306a1c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
