"""primeiro migrate

Revision ID: a85e306a1c28
Revises: c4629ef3c836
Create Date: 2021-06-26 22:15:45.929622

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a85e306a1c28'
down_revision = 'c4629ef3c836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('address', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('social_networks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_networks_id'), 'social_networks', ['id'], unique=True)
    op.drop_index('ix_posts_id', table_name='posts')
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=True)
    op.drop_index('ix_project_posts_id', table_name='project_posts')
    op.create_index(op.f('ix_project_posts_id'), 'project_posts', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_posts_id'), table_name='project_posts')
    op.create_index('ix_project_posts_id', 'project_posts', ['id'], unique=False)
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.drop_index(op.f('ix_social_networks_id'), table_name='social_networks')
    op.drop_table('social_networks')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
